baseURL = 'https://adamh2009.github.io/'
languageCode = 'en-gb'
title = 'My Landing Page'
theme = 'startpage'

[[params.searchEngines]]
  name = "Google"
  activated = true
  url = "https://www.google.com/search"
